---
title: "phylo"
author: "D.Smutin"
date: "2024-10-31"
output: html_document
---

# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggtree)
library(ape)

mms <- function(x) (x - min(x, na.rm = T)) / 
    (max(x, na.rm = T)-min(x, na.rm = T))
```

#### misc
```{bash}
for f in *\ *; do mv "$f" "${f// /_}"; done

mkdir ../align
for file in $(ls); do
  nm=$(grep ">" "$file" | wc -l)
  if [ $nm -gt 1 ]; then
    echo $nm
    mafft "$file" > ../align/$file.aligned
  else
    cat "$file" > ../align/$file.aligned
  fi
done
```

```{r}
library(seqinr)
library(Biostrings)
cons <- function(path){
  fa <- readDNAStringSet(path)
  cons <- fa %>% consensusString(ambiguityMap = "N", threshold = 0.1)
}
path <- "../data/fasta/align/Acromyrmex_echinatior.fas.aligned"
```



# Read tree
```{r rt}
leg <- readxl::read_xlsx("../data/legends/TE_101_annot.xlsx") %>% 
  rename("label"="SP") %>% 
  mutate(repeats = apply(.[,-c(1:4)], 1, sum))
colnames(leg) <- colnames(leg) %>% str_remove_all("[?:]")

# Read files, combine with legend and drop tips which are not represented
rb <- function(path) {
  tmp <- (read.nexus(path) %>% ggtree)$data %>% 
    mutate(label = label %>% 
             str_replace("_", " ") %>% 
             str_remove("_.*")) %>% 
    left_join(leg, by = "label")
}

rn <- function(path) {
  tmp <- (read.tree(path) %>% ggtree)$data %>% 
    mutate(label = label %>% 
             str_replace("_", " ") %>% 
             str_remove("_.*")) %>% 
    left_join(leg, by = "label")
}

rt <- function(path) {
  tmp <- (read.nexus(path) %>% ggtree(
    #branch.length = 'none'
    ))$data %>% 
    mutate(label = label %>% 
             str_replace("_", " ") %>% 
             str_remove("_.*")) %>% 
    left_join(leg, by = "label")
}

d1 <- rb("../data/tree/beast/hymen16s.out.nex")
d2 <- rb("../data/tree/beast/hymenCOX.out.nex")
d3 <- rn("../data/tree/nj/hymen16s.nwk")
d4 <- rn("../data/tree/nj/hymenCOXI.nwk")

d5 <- rt("../data/tree/new/mrbayes.tre")
d6 <- rn("../data/tree/new/tree.nwk")
```

# Compare
```{r}
ggcompare <- function(d1, d2) {
  # main code from https://yulab-smu.top/treedata-book/chapter2.html
  d1$x <- mms(d1$x)
  d2$x <- mms(d2$x)

  ## reverse x-axis and
  d2$x <- max(d2$x) - d2$x + max(d1$x) + .5

  pp <- ggtree(d1, aes(color = as.numeric(label))) +
    geom_tree(data = d2, aes(color = as.numeric(label), x = x + .2)) +
    theme(legend.position = "bottom") +
    scale_color_gradient(name = "confidence", low = "lightgreen", high = "darkgreen", na.value = "darkgreen")


    dd <- bind_rows(
      d1[d1$label %in% d2$label, ],
      d2[d2$label %in% d1$label, ]
    ) %>%
      filter(!is.na(label)) %>% 
      subset(isTip)

    gg <- pp +
      ggnewscale::new_scale_color() +
      geom_line(
        aes(x, y,
          group = label,
          color = Family
        ),
        data = dd, alpha = .1
      ) +
      #scale_color_brewer("", palette = "Set2", na.value = "gray") +
      geom_tiplab(data = d2, hjust = 0, aes(x = x, color = Family), size = 2) 
    print(gg)
    gg
}

gg <- ggcompare(
  d2,d1
)
ggsave("g1.png", gg, width = 3000, height = 1400, units = "px")

gg <- ggcompare(
  d3,d4
)
ggsave("g2.png", gg, width = 3000, height = 1400, units = "px")

gg <- ggcompare(
  d2,d4
)
ggsave("g3.png", gg, width = 3000, height = 1400, units = "px")

gg <- ggcompare(
  d5,d6
)
ggsave("g4.png", gg, width = 3000, height = 1400, units = "px")
```

#depr
```{r}
d1$x <- mms(d1$x)
  d2$x <- mms(d2$x) + max(d1$x, na.rm = T) + .3
  d3$x <- mms(d3$x) + max(d2$x, na.rm = T) + .3
  d4$x <- mms(d4$x) + max(d3$x, na.rm = T) + .3
  
  dd = bind_rows(d1, d2, d3, d4) %>% 
    filter(!is.na(label)) %>% 
    subset(isTip)
  
  ggtree(d1, aes(color = label %>% as.numeric())) + 
    geom_tree(data = d2, aes(color = label%>% as.numeric())) + 
    geom_tree(data = d3, aes(color = label%>% as.numeric())) + 
    geom_tree(data = d4, aes(color = label%>% as.numeric())) + 
    
    scale_color_gradient(name = "confidence", low = "lightgreen", high = "darkgreen", na.value = "darkgreen") +
    
    ggnewscale::new_scale_color() +
    geom_tiplab(data = d3, aes(label = label), show.legend = F) + 
    geom_line(aes(x, y, group=label), data=dd, alpha=.3, show.legend = F) +
    theme(legend.position = "bottom")
```


# Eusociality
```{r}
gg <- ggtree(d6, aes(color = as.numeric(label)), 
            # layout = "circular"
             ) +
  ggnewscale::new_scale_color() +
  geom_tippoint(aes(color = Social)) +
  ggnewscale::new_scale_color() +
  geom_tiplab(size = 2,align=TRUE, aes(color = Family), show.legend = F) +
  ggnewscale::new_scale_color() +
  theme_tree2()

ggsave("g6.png", gg, width = 3000, height = 1400, units = "px")
```

# Add data
```{r}
gg + geom_facet(panel = "repeats", 
                data = leg,
                geom = geom_col,
                mapping = aes(x = repeats, 
                              color = Social))
```


```{r}
hmp <- (leg %>% column_to_rownames("label"))[,-c(1:4, 23)] %>% 
  na.omit %>% 
  apply(2, mms)
gg2 <- gheatmap(gg, hmp, offset=.2, width=1, 
        colnames=F, legend_title="amount") +
  scale_fill_gradient("% of elements",
                      low = "lightgreen", high="tomato",
                      na.value = "transparent") +
    scale_x_ggtree() + 
    scale_y_continuous(expand=c(0, 1)) +
  theme(axis.text.x = element_text(angle = 30, hjust= 1, size = 5),
        legend.position = "bottom")
ggsave("g8.png", gg2, width = 3600, height = 1800, units = "px")
```

# more pretty
```{r}
gg <- ggtree(d6, layout = "circular",
            branch.length = "none"
             ) +
  ggnewscale::new_scale_color() +
  geom_tippoint(aes(color = Social)) +
  ggnewscale::new_scale_color() +
  geom_tiplab(data = d6, size = 2,align=TRUE, aes(color = Family, label = ""), show.legend = F) +
  ggnewscale::new_scale_color() 


gg2 <- gheatmap(gg, hmp, offset=.2, width=1, 
        colnames=F, legend_title="amount") +
  scale_fill_gradient("% of elements",
                      low = "lightgreen", high="tomato",
                      na.value = "transparent") +
    scale_y_continuous(expand=c(0, .1)) +
  theme_tree() +
  theme(axis.text = element_text())

ggsave("g9.png", gg2, width = 3000, height = 2500, units = "px")
```





# Cophenetic permanova
```{r}
library(vegan)

hmp <- (leg %>% column_to_rownames("label"))[,-c(1:4, 23)] %>% 
  na.omit %>% apply(2, mms)
colnames(hmp) <- colnames(hmp) %>% 
  str_replace_all("[/ -]", "_")

coph <- cophenetic.phylo(d6 %>% as.phylo) %>% 
  as.data.frame() %>% 
  subset(rownames(.) %in% rownames(hmp)) %>% t %>% 
  subset(rownames(.) %in% rownames(hmp)) %>% 
  as.data.frame()

hmp <- hmp %>% 
  subset(rownames(.) %in% rownames(coph)) %>% 
  as.data.frame()

#colnames(hmp) %>% paste0(collapse = " + ") %>%  cat

for ( i in colnames(hmp) ) {
  adform <- as.formula(paste0("coph ~ ", i))
  cat(i,"\n") 
  adres <- adonis2(adform,data = hmp)
  cat("####","\n","\n")
}
```

# permanova eusoc
```{r}
socvec <- leg[match(rownames(hmp),leg$label),"Social"] %>% 
  mutate(Social = ifelse(
    Social %in% c("YES", "NO"),
    Social,
    "PART"
  ))

res <- adonis2(hmp~Social,
               data = socvec, 
               #method = "euclidian",
               by = "onedf")
```

# Barplots
```{r}
hmp2 <- hmp %>% 
  rownames_to_column("sp") %>% 
  mutate(Social = socvec$Social) %>% 
  pivot_longer(cols = -c(1, 20)) 
  
library(ggpubr)

gg <- hmp2 %>%
  mutate(name = fct_inorder(name)) %>% 
  ggplot(aes(fill = Social, y = "", x = value)) +
  geom_boxplot() +
  facet_wrap(~name, scales = "free") +
  theme_minimal()

ggsave("g10.png", gg, width = 2200, height = 1500, units = "px")

cmp <- list(c("YES","NO"),c("YES", "PART"),c("NO", "PART"))

for (i in unique(hmp2$name)) {
  
ggp <- hmp2 %>% 
  mutate(Social = fct_rev(Social)) %>% 
  subset(name == i) %>% 
  ggboxplot(x = "Social", y = "value",
          color = "Social", 
          palette =c("#00AFBB", "#E7B800", "#FC4E07"),
          add = "jitter", shape = "name") +
  #facet_wrap(~name, scales = "free") +
  theme_minimal() + 
  theme(legend.position = "none",
        #axis.text.x = element_blank()
        ) +
  stat_compare_means(comparisons = cmp, label = "p.signif") +
  ggtitle(i) +
  xlab("sociality")

ggsave(paste0("pubr/",i,".png"), ggp, width = 1000, height = 1000, units = "px")
}
```

# CCA
```{r}
require(ggplot2)
require(GGally)
require(CCA)
require(CCP)
```

